language: node_js
node_js:
- "8"
os:
- linux
- osx
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - p7zip-full
  ssh_known_hosts: savagecore.eu

before_script:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install rpm; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew update && brew install p7zip; fi
  - chmod a+x ./ci/travis.sh

install:
- npm install -g npm
- npm install
- npm install electron-packager -g

script:
 - npm --version
 - npm run test

after_script:
 - ./ci/travis.sh

before_install:
- openssl aes-256-cbc -K $encrypted_977674b441f6_key -iv $encrypted_977674b441f6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
